import Head from 'next/head'

import Navbar from '../components/Navbar';
import Header from '../components/Header';
import About from '../components/About';
import Works from '../components/Works'
import Contact from '../components/Contact'
import Footer from '../components/Footer';

export default function Home() {


  return (
    <div>
      <Head>
        <title>Taha Yeşilbağ | Ön Yüz Geliştirici</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
      <Header />
      <About />
      <Works />
      <Contact />
      <Footer />
    </div>
  )
}
